/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.pzstorm.capsid;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'io.pzstorm.capsid.greeting' plugin.
 */
public class CapsidPluginTest {

    @Test
    public void pluginRegistersATask() {

        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("io.pzstorm.capsid.greeting");

        // Verify the result
        assertNotNull(project.getTasks().findByName("greeting"));
    }
}
